FROM cypress/included:14.5.1

WORKDIR /e2e

# Copiamos dependencias primero para aprovechar cache
COPY package*.json ./

RUN npm install

# Ahora copiamos el resto del proyecto
COPY . .

# Ejecutar cypress en modo headless con reporter
CMD ["npm", "run", "cy:run"]
